name: wathiq
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  animated_splash_screen: ^1.3.0
  convex_bottom_bar: ^3.2.0
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.9.1
  video_player: ^2.10.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true


  assets:
    - assets/videos/
    - assets/images/
